name: PowerShell Tests & Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install required modules
        shell: pwsh
        run: |
          Install-Module Pester -Force -Scope CurrentUser
          Install-Module PSCodeHealth -Force -Scope CurrentUser

      - name: Run Pester Tests
        shell: pwsh
        run: |
          Invoke-Pester -Path .\Tests -OutputFormat NUnitXml `
            -OutputFile TestResults.xml `
            -CodeCoverageOutputFile CodeCoverage.xml

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage
          path: CodeCoverage.xml
